name: Healio Workflow
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: check linting
        run: |
          echo "Running next lint"
          if ! npm run lint; then
            echo "fix the linting issues"
            exit 1
          fi

      - name: success notify
        if: success()
        run: echo "Successfully linted"

  test-cases:
    name: Tests
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: testing
        run: |
          echo "Running test cases"
          npm run test:coverage

      - name: collect coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 2
          if-no-files-found: warn

      - name: failure
        if: failure()
        run: echo "test cases failed please check"
